name: TED Konkursai

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secre
